import { Order } from "@/types";

export const orders: Order[] = [
  {
    id: "o-1001",
    orderNumber: "RG-100234",
    date: "2026-07-01",
    status: "Delivered",
    items: [
      {
        productId: "p-legacy",
        productName: "Legacy",
        productSlug: "legacy",
        image: "/products/legacy.svg",
        variantSize: "50ml",
        quantity: 1,
        unitPrice: 285,
      },
    ],
    subtotal: 285,
    shipping: 15,
    tax: 14.25,
    discount: 0,
    total: 314.25,
    trackingNumber: "RG-TRK-88213",
    trackingEvents: [
      { status: "Pending", date: "2026-07-01", note: "Order placed" },
      { status: "Processing", date: "2026-07-01", note: "Payment confirmed, preparing order" },
      { status: "Shipped", date: "2026-07-02", note: "Handed to courier" },
      { status: "Delivered", date: "2026-07-04", note: "Delivered to recipient" },
    ],
    shippingAddress: {
      fullName: "Rita Green",
      line1: "14 Admiralty Way",
      line2: "Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "106104",
      phone: "+234 803 000 1122",
    },
    paymentMethod: "Paystack (Card)",
  },
  {
    id: "o-1002",
    orderNumber: "RG-100519",
    date: "2026-07-10",
    status: "Shipped",
    items: [
      {
        productId: "p-noir",
        productName: "Noir",
        productSlug: "noir",
        image: "/products/noir.svg",
        variantSize: "100ml",
        quantity: 1,
        unitPrice: 445,
      },
      {
        productId: "p-elite",
        productName: "Elite",
        productSlug: "elite",
        image: "/products/elite.svg",
        variantSize: "50ml",
        quantity: 2,
        unitPrice: 255,
      },
    ],
    subtotal: 955,
    shipping: 0,
    tax: 47.75,
    discount: 95.5,
    total: 907.25,
    trackingNumber: "RG-TRK-90144",
    trackingEvents: [
      { status: "Pending", date: "2026-07-10", note: "Order placed" },
      { status: "Processing", date: "2026-07-10", note: "Payment confirmed, preparing order" },
      { status: "Shipped", date: "2026-07-12", note: "Handed to courier" },
    ],
    shippingAddress: {
      fullName: "Rita Green",
      line1: "14 Admiralty Way",
      line2: "Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "106104",
      phone: "+234 803 000 1122",
    },
    paymentMethod: "Stripe (Card)",
  },
  {
    id: "o-1003",
    orderNumber: "RG-100822",
    date: "2026-07-14",
    status: "Processing",
    items: [
      {
        productId: "p-royale",
        productName: "Royale",
        productSlug: "royale",
        image: "/products/royale.svg",
        variantSize: "50ml",
        quantity: 1,
        unitPrice: 295,
      },
    ],
    subtotal: 295,
    shipping: 15,
    tax: 14.75,
    discount: 0,
    total: 324.75,
    trackingEvents: [
      { status: "Pending", date: "2026-07-14", note: "Order placed" },
      { status: "Processing", date: "2026-07-14", note: "Payment confirmed, preparing order" },
    ],
    shippingAddress: {
      fullName: "Rita Green",
      line1: "14 Admiralty Way",
      line2: "Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      country: "Nigeria",
      postalCode: "106104",
      phone: "+234 803 000 1122",
    },
    paymentMethod: "Bank Transfer",
  },
];

export function getOrderByNumber(orderNumber: string): Order | undefined {
  return orders.find((o) => o.orderNumber === orderNumber);
}
